config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }

  resources :users, :only => [:index]

  # get "pages/home" => "pages#home"

  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 50 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord

  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord

  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  belongs_to :user

  has_many :comments

  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos

end

app/models/user.rb
class User < ApplicationRecord

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :posts, dependent: :destroy

  has_many :comments

  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  validates :image, presence: true

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.limit(10).includes(:photos, :user)
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(9)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @like = Like.new
    @comments = @post.comments
    @comment = Comment.new
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:food_name, :store_name, :description, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order('created_at DESC').page(params[:page]).per(9)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/navbar' if current_user %>

    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>

app/views/partial/_navbar.html.erb
<div class="container">
<header class="header">
      <heading class="heading">
        <%= link_to("Delivery App", "/", {class: "heading-delivery-app"} ) %>
      </heading>
      <div class="navbar">
        <ul class="nav-lists">
          <%# 飛行機マーク 新規投稿 %>
          <%= link_to new_post_path, :method => :get do %>
            <li class="light three"><i class="fa fa-paper-plane fa-3x fa-sandybrown"></i></li>
          <% end %>
          <%# ユーザー一覧 %>
          <%= link_to users_path, :method => :get do %>
            <li class="light three"><i class="fa fa-users fa-3x fa-sandybrown"></i></li>
          <% end %>

          <%# メニュー ドロップダウン %>
          <li class="menu three">
            <div class="dropdown">
            	<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
            		MENU
            		<span class="caret"></span>
            	</button>
              <ul class="dropdown-menu" role="menu">
                <%# マイページ %>
              	<%= link_to user_path(current_user), method: :get do %>
                  <li role="presentation">マイページ</li>
                <% end %>

                <%# 編集 %>
                <%= link_to edit_user_registration_path, method: :get do %>
              	  <li role="presentation">編集</li>
                <% end %>

                <%# 新規投稿 %>
                <%= link_to new_post_path, :method => :get do %>
              	  <li role="presentation">新規投稿</li>
                <% end %>

                <%# ユーザー一覧 %>
                <%= link_to users_path, :method => :get do %>
              	  <li role="presentation">ユーザー一覧</li>
                <% end %>

                <%# ログアウト %>
              	<li role="presentation">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </header>
</div>

app/views/posts/index.html.erb
<div>
<%# 検索機能 %>
  <div class="search">
    <%= search_form_for @q do |f| %>
      <span class="search-br">
        <%= f.label :food_name, "食べ物名:" %>
        <%= f.search_field :food_name_cont %>
      </span>
      <span class="search-br2">
        <%= f.label :store_name, "店名:" %>
        <%= f.search_field :store_name_cont %>
      </span>
      <%= f.submit "検索" %>
    <% end %>
  </div>
<%# 投稿一覧 %>
  <div class="post">
    <div class="grand-wrap">
      <% @posts.each do |post| %>
        <div class="parent-wrap col-md-4 col-sm-4 col-xs-12">
            <%# 画像 %>
            <div class="child-wrap post-image">
              <%= link_to(post_path(post)) do %>
                <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
              <% end %>
            </div>
            <%# 画像の下 %>
            <table class="table">
              <tbody>
                <tr>
                    <th>食べ物名:<%= post.food_name %></th>
                </tr>
                <tr>
                    <th>店名:<%= post.store_name %></th>
                </tr>
                <tr>
                    <th>❤️ (<%= post.liked_users.count %>)</th>
                </tr>
                <tr>
                    <th></th>
                </tr>
              </tbody>
            </table>
        </div>
      <% end %>
    </div>
  </div>
<%# ページネーション %>
  <div class="pagenation">
    <div class="paginate">
      <%= paginate @posts %>
    </div>
  </div>

</div>

app/views/posts/new.html.erb
<div class="text-center">
  <%= form_with model: @post do |f| %>
    <%# 画像 %>
      <div class="new-item">
      料理の写真:<%= f.fields_for :photos do |i| %>
        <%= i.file_field :image %>
      <% end %>
      </div>
    <%# 食べ物 %>
      <div class="new-item">
        <%= f.label :料理 %>
        <%= f.text_field :food_name %>
      </div>
    <%# 店名 %>
      <div class="new-item">
        <%= f.label :店名 %>
        <%= f.text_field :store_name %>
      </div>
    <%# 説明 %>
      <div class="new-item">
        <p class="new-description"><%= f.label :説明 %></p>
        <%= f.text_area :description, :size=>"35x5" %>
      </div>
    <%# 投稿 %>
      <div class="new-button">
        <%= f.submit "投稿", class: "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%# 画像 %>
<%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top show-image" %>

<table class="table table-adjustment">
  <tbody>
    <tr>
        <th>食べ物名:<%= @post.food_name %></th>
    </tr>
    <tr>
        <th>店名:<%= @post.store_name %></th>
    </tr>
    <tr>
        <th>説明:<%= @post.description %></th>
    </tr>
    <tr>
        <th></th>
    </tr>
  </tbody>
</table>

<%# いいね機能 %>
<div class="like-container">
  <div class="like-show">
    <h3>❤️: <%= @post.likes.count %></h3>
  </div>
  <div class="like-show like-delete">
    <% if current_user.already_liked?(@post) %>
      <%= button_to '❤️ を取り消す', post_like_path(@post), method: :delete %>
    <% else %>
      <%= button_to '❤️', post_likes_path(@post) %>
    <% end %>
  </div>
</div>
<div class="like-show">
  <h4>❤️を押したユーザー↓</h4>
</div>

<div class="like-show grand-wrap-show">
  <% @post.liked_users.each do |user| %>
    <div class="parent-wrap-show col-md-3 col-sm-3 col-xs-3">
      <div class="child-wrap-show">
        <img src=<%= user.image %> class = "icon_image-user-show">
      </div>
      <div class="child-wrap-show">
        <%= user.name %>
      </div>
    </div>
  <% end %>
</div>

<%# コメントが表示される %>
<h2 class="comment-padding">コメント一覧</h2>
<% @comments.each do |c| %>
  <div>
    <%= c.user.name %>さん:</a>
    <%= c.content %>
    <hr>
  </div>
<% end %>

<%# コメントを入力 %>
<%= form_for [@post, @comment] do |f| %>
  <div class="comment-inline">
    <%= f.text_field :content %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <br>
    <div class="comment-btn">
      <%= f.submit 'コメントする', class: "btn btn-primary btn-padding" %>
    </div>
  </div>
<% end %>

<div class="post-show-btn">
  <%# ホームへ戻るボタン %>
  <div class="post-show-back">
    <%= link_to "戻る", root_path, class: 'btn btn-primary' %>
  </div>

  <%# 削除ボタン %>
  <div class="post-show-delete">
    <% if @post.user_id == current_user.id %>
      <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
        <%# <div class="delete-post-icon">
          削除
        </div> %>
        <p><button type="button" class="btn btn-danger delete-post-icon">削除</button></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div>

  <div class="grand-wrap-users">
    <% @users.each do |user| %>
      <div class="parent-wrap-users col-md-4">
        <div class="child-wrap-users">
          <img src=<%= user.image %> class = "icon_image">
        </div>
        <div class="child-wrap-users">
          <a href="/users/<%= user.id %>"><%= user.name %></a>
        </div>
      </div>
    <% end %>
  </div>

  <div class="pagenation">
    <div class="paginate-users">
      <%= paginate @users %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="icon_image-user-show-1 user-adjust">
  <img src=<%= @user.image %> class = "icon_image-user-show">
</div>

<div class="user-name-show user-adjust">
  <h1><%= @user.name %>さんの詳細ページ</h1>
</div>

<div class="profile-user-show user-adjust">
<% if @user == current_user %>
  <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark edit-profile-btn" %>
<% end %>
</div>

<div class="like-user-show">
  <h3>いいねしている投稿↓</h3>
</div>

<% @user.liked_posts.each do |post| %>
  <%= link_to(post_path(post)) do %>
    <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top-2" %>
  <% end %>
  <div class="like-background">
    <div class="show-foodname">
      食べ物名:<%= post.food_name %>
    </div>
    <div class="show-storename">
      店名:<%= post.store_name %>
    </div>
  </div>
<% end %>